class GeoLocationService

  @@countries = [
      {:alpha2=>"AF", :name=>"Afghanistan", :alpha3=>"AFG"},
      {:alpha2=>"AL", :name=>"Albania", :alpha3=>"ALB"},
      {:alpha2=>"DZ", :name=>"Algeria", :alpha3=>"DZA"},
      {:alpha2=>"AS", :name=>"American Samoa", :alpha3=>"ASM"},
      {:alpha2=>"AD", :name=>"Andorra", :alpha3=>"AND"},
      {:alpha2=>"AO", :name=>"Angola", :alpha3=>"AGO"},
      {:alpha2=>"AI", :name=>"Anguilla", :alpha3=>"AIA"},
      {:alpha2=>"AQ", :name=>"Antarctica", :alpha3=>"ATA"},
      {:alpha2=>"AG", :name=>"Antigua And Barbuda", :alpha3=>"ATG"},
      {:alpha2=>"AR", :name=>"Argentina", :alpha3=>"ARG"},
      {:alpha2=>"AM", :name=>"Armenia", :alpha3=>"ARM"},
      {:alpha2=>"AW", :name=>"Aruba", :alpha3=>"ABW"},
      {:alpha2=>"AC", :name=>"Ascension Island", :alpha3=>"ASC"},
      {:alpha2=>"AU", :name=>"Australia", :alpha3=>"AUS"},
      {:alpha2=>"AT", :name=>"Austria", :alpha3=>"AUT"},
      {:alpha2=>"AZ", :name=>"Azerbaijan", :alpha3=>"AZE"},
      {:alpha2=>"BS", :name=>"Bahamas", :alpha3=>"BHS"},
      {:alpha2=>"BH", :name=>"Bahrain", :alpha3=>"BHR"},
      {:alpha2=>"BD", :name=>"Bangladesh", :alpha3=>"BGD"},
      {:alpha2=>"BB", :name=>"Barbados", :alpha3=>"BRB"},
      {:alpha2=>"BY", :name=>"Belarus", :alpha3=>"BLR"},
      {:alpha2=>"BE", :name=>"Belgium", :alpha3=>"BEL"},
      {:alpha2=>"BZ", :name=>"Belize", :alpha3=>"BLZ"},
      {:alpha2=>"BJ", :name=>"Benin", :alpha3=>"BEN"},
      {:alpha2=>"BM", :name=>"Bermuda", :alpha3=>"BMU"},
      {:alpha2=>"BT", :name=>"Bhutan", :alpha3=>"BTN"},
      {:alpha2=>"BO", :name=>"Bolivia", :alpha3=>"BOL"},
      {:alpha2=>"BA", :name=>"Bosnia And Herzegovina", :alpha3=>"BIH"},
      {:alpha2=>"BW", :name=>"Botswana", :alpha3=>"BWA"},
      {:alpha2=>"BV", :name=>"Bouvet Island", :alpha3=>"BVT"},
      {:alpha2=>"BR", :name=>"Brazil", :alpha3=>"BRA"},
      {:alpha2=>"IO", :name=>"British Indian Ocean Territory", :alpha3=>"IOT"},
      {:alpha2=>"BN", :name=>"Brunei", :alpha3=>"BRN"},
      {:alpha2=>"BG", :name=>"Bulgaria", :alpha3=>"BGR"},
      {:alpha2=>"BF", :name=>"Burkina Faso", :alpha3=>"BFA"},
      {:alpha2=>"BI", :name=>"Burundi", :alpha3=>"BDI"},
      {:alpha2=>"KH", :name=>"Cambodia", :alpha3=>"KHM"},
      {:alpha2=>"CM", :name=>"Cameroon", :alpha3=>"CMR"},
      {:alpha2=>"CA", :name=>"Canada", :alpha3=>"CAN"},
      {:alpha2=>"CV", :name=>"Cape Verde", :alpha3=>"CPV"},
      {:alpha2=>"KY", :name=>"Cayman Islands", :alpha3=>"CYM"},
      {:alpha2=>"CF", :name=>"Central African Republic", :alpha3=>"CAF"},
      {:alpha2=>"TD", :name=>"Chad", :alpha3=>"TCD"},
      {:alpha2=>"CL", :name=>"Chile", :alpha3=>"CHL"},
      {:alpha2=>"CN", :name=>"China", :alpha3=>"CHN"},
      {:alpha2=>"CX", :name=>"Christmas Island", :alpha3=>"CXR"},
      {:alpha2=>"CC", :name=>"Cocos (Keeling) Islands", :alpha3=>"CCK"},
      {:alpha2=>"CO", :name=>"Columbia", :alpha3=>"COL"},
      {:alpha2=>"KM", :name=>"Comoros", :alpha3=>"COM"},
      {:alpha2=>"CG", :name=>"Congo", :alpha3=>"COG"},
      {:alpha2=>"CK", :name=>"Cook Islands", :alpha3=>"COK"},
      {:alpha2=>"CR", :name=>"Costa Rica", :alpha3=>"CRI"},
      {:alpha2=>"CI", :name=>"Cote D'Ivorie (Ivory Coast)", :alpha3=>"CIV"},
      {:alpha2=>"HR", :name=>"Croatia (Hrvatska)", :alpha3=>"HRV"},
      {:alpha2=>"CU", :name=>"Cuba", :alpha3=>"CUB"},
      {:alpha2=>"CY", :name=>"Cyprus", :alpha3=>"CYP"},
      {:alpha2=>"CZ", :name=>"Czech Republic", :alpha3=>"CZE"},
      {:alpha2=>"CD", :name=>"Democratic Republic Of Congo (Zaire)", :alpha3=>"COD"},
      {:alpha2=>"DK", :name=>"Denmark", :alpha3=>"DNK"},
      {:alpha2=>"DJ", :name=>"Djibouti", :alpha3=>"DJI"},
      {:alpha2=>"DM", :name=>"Dominica", :alpha3=>"DMA"},
      {:alpha2=>"DO", :name=>"Dominican Republic", :alpha3=>"DOM"},
      {:alpha2=>"TL", :name=>"East Timor", :alpha3=>"TLS"},
      {:alpha2=>"EC", :name=>"Ecuador", :alpha3=>"ECU"},
      {:alpha2=>"EG", :name=>"Egypt", :alpha3=>"EGY"},
      {:alpha2=>"SV", :name=>"El Salvador", :alpha3=>"SLV"},
      {:alpha2=>"GQ", :name=>"Equatorial Guinea", :alpha3=>"GNQ"},
      {:alpha2=>"ER", :name=>"Eritrea", :alpha3=>"ERI"},
      {:alpha2=>"EE", :name=>"Estonia", :alpha3=>"EST"},
      {:alpha2=>"ET", :name=>"Ethiopia", :alpha3=>"ETH"},
      {:alpha2=>"FK", :name=>"Falkland Islands (Malvinas)", :alpha3=>"FLK"},
      {:alpha2=>"FO", :name=>"Faroe Islands", :alpha3=>"FRO"},
      {:alpha2=>"FJ", :name=>"Fiji", :alpha3=>"FJI"},
      {:alpha2=>"FI", :name=>"Finland", :alpha3=>"FIN"},
      {:alpha2=>"FR", :name=>"France", :alpha3=>"FRA"},
      {:alpha2=>"FX", :name=>"France, Metropolitan", :alpha3=>nil},
      {:alpha2=>"GF", :name=>"French Guinea", :alpha3=>"GUF"},
      {:alpha2=>"PF", :name=>"French Polynesia", :alpha3=>"PYF"},
      {:alpha2=>"TF", :name=>"French Southern Territories", :alpha3=>"ATF"},
      {:alpha2=>"GA", :name=>"Gabon", :alpha3=>"GAB"},
      {:alpha2=>"GM", :name=>"Gambia", :alpha3=>"GMB"},
      {:alpha2=>"GE", :name=>"Georgia", :alpha3=>"GEO"},
      {:alpha2=>"DE", :name=>"Germany", :alpha3=>"DEU"},
      {:alpha2=>"GH", :name=>"Ghana", :alpha3=>"GHA"},
      {:alpha2=>"GI", :name=>"Gibraltar", :alpha3=>"GIB"},
      {:alpha2=>"GR", :name=>"Greece", :alpha3=>"GRC"},
      {:alpha2=>"GL", :name=>"Greenland", :alpha3=>"GRL"},
      {:alpha2=>"GD", :name=>"Grenada", :alpha3=>"GRD"},
      {:alpha2=>"GP", :name=>"Guadeloupe", :alpha3=>"GLP"},
      {:alpha2=>"GU", :name=>"Guam", :alpha3=>"GUM"},
      {:alpha2=>"GT", :name=>"Guatemala", :alpha3=>"GTM"},
      {:alpha2=>"GN", :name=>"Guinea", :alpha3=>"GIN"},
      {:alpha2=>"GW", :name=>"Guinea-Bissau", :alpha3=>"GNB"},
      {:alpha2=>"GY", :name=>"Guyana", :alpha3=>"GUY"},
      {:alpha2=>"HT", :name=>"Haiti", :alpha3=>"HTI"},
      {:alpha2=>"HM", :name=>"Heard And McDonald Islands", :alpha3=>"HMD"},
      {:alpha2=>"HN", :name=>"Honduras", :alpha3=>"HND"},
      {:alpha2=>"HK", :name=>"Hong Kong", :alpha3=>"HKG"},
      {:alpha2=>"HU", :name=>"Hungary", :alpha3=>"HUN"},
      {:alpha2=>"IS", :name=>"Iceland", :alpha3=>"ISL"},
      {:alpha2=>"IN", :name=>"India", :alpha3=>"IND"},
      {:alpha2=>"ID", :name=>"Indonesia", :alpha3=>"IDN"},
      {:alpha2=>"IR", :name=>"Iran", :alpha3=>"IRN"},
      {:alpha2=>"IQ", :name=>"Iraq", :alpha3=>"IRQ"},
      {:alpha2=>"IE", :name=>"Ireland", :alpha3=>"IRL"},
      {:alpha2=>"IM", :name=>"Isle of Man", :alpha3=>"IMN"},
      {:alpha2=>"IL", :name=>"Israel", :alpha3=>"ISR"},
      {:alpha2=>"IT", :name=>"Italy", :alpha3=>"ITA"},
      {:alpha2=>"JM", :name=>"Jamaica", :alpha3=>"JAM"},
      {:alpha2=>"JP", :name=>"Japan", :alpha3=>"JPN"},
      {:alpha2=>"JO", :name=>"Jordan", :alpha3=>"JOR"},
      {:alpha2=>"KZ", :name=>"Kazakhstan", :alpha3=>"KAZ"},
      {:alpha2=>"KE", :name=>"Kenya", :alpha3=>"KEN"},
      {:alpha2=>"KI", :name=>"Kiribati", :alpha3=>"KIR"},
      {:alpha2=>"KW", :name=>"Kuwait", :alpha3=>"KWT"},
      {:alpha2=>"KG", :name=>"Kyrgyzstan", :alpha3=>"KGZ"},
      {:alpha2=>"LA", :name=>"Laos", :alpha3=>"LAO"},
      {:alpha2=>"LV", :name=>"Latvia", :alpha3=>"LVA"},
      {:alpha2=>"LB", :name=>"Lebanon", :alpha3=>"LBN"},
      {:alpha2=>"LS", :name=>"Lesotho", :alpha3=>"LSO"},
      {:alpha2=>"LR", :name=>"Liberia", :alpha3=>"LBR"},
      {:alpha2=>"LY", :name=>"Libya", :alpha3=>"LBY"},
      {:alpha2=>"LI", :name=>"Liechtenstein", :alpha3=>"LIE"},
      {:alpha2=>"LT", :name=>"Lithuania", :alpha3=>"LTU"},
      {:alpha2=>"LU", :name=>"Luxembourg", :alpha3=>"LUX"},
      {:alpha2=>"MO", :name=>"Macau", :alpha3=>"MAC"},
      {:alpha2=>"MK", :name=>"Macedonia", :alpha3=>"MKD"},
      {:alpha2=>"MG", :name=>"Madagascar", :alpha3=>"MDG"},
      {:alpha2=>"MW", :name=>"Malawi", :alpha3=>"MWI"},
      {:alpha2=>"MY", :name=>"Malaysia", :alpha3=>"MYS"},
      {:alpha2=>"MV", :name=>"Maldives", :alpha3=>"MDV"},
      {:alpha2=>"ML", :name=>"Mali", :alpha3=>"MLI"},
      {:alpha2=>"MT", :name=>"Malta", :alpha3=>"MLT"},
      {:alpha2=>"MH", :name=>"Marshall Islands", :alpha3=>"MHL"},
      {:alpha2=>"MQ", :name=>"Martinique", :alpha3=>"MTQ"},
      {:alpha2=>"MR", :name=>"Mauritania", :alpha3=>"MRT"},
      {:alpha2=>"MU", :name=>"Mauritius", :alpha3=>"MUS"},
      {:alpha2=>"YT", :name=>"Mayotte", :alpha3=>"MYT"},
      {:alpha2=>"MX", :name=>"Mexico", :alpha3=>"MEX"},
      {:alpha2=>"FM", :name=>"Micronesia", :alpha3=>"FSM"},
      {:alpha2=>"MD", :name=>"Moldova", :alpha3=>"MDA"},
      {:alpha2=>"MC", :name=>"Monaco", :alpha3=>"MCO"},
      {:alpha2=>"MN", :name=>"Mongolia", :alpha3=>"MNG"},
      {:alpha2=>"ME", :name=>"Montenegro", :alpha3=>"MNE"},
      {:alpha2=>"MS", :name=>"Montserrat", :alpha3=>"MSR"},
      {:alpha2=>"MA", :name=>"Morocco", :alpha3=>"MAR"},
      {:alpha2=>"MZ", :name=>"Mozambique", :alpha3=>"MOZ"},
      {:alpha2=>"MM", :name=>"Myanmar (Burma)", :alpha3=>"MMR"},
      {:alpha2=>"NA", :name=>"Namibia", :alpha3=>"NAM"},
      {:alpha2=>"NR", :name=>"Nauru", :alpha3=>"NRU"},
      {:alpha2=>"NP", :name=>"Nepal", :alpha3=>"NPL"},
      {:alpha2=>"NL", :name=>"Netherlands", :alpha3=>"NLD"},
      {:alpha2=>"AN", :name=>"Netherlands Antilles", :alpha3=>"ANT"},
      {:alpha2=>"NC", :name=>"New Caledonia", :alpha3=>"NCL"},
      {:alpha2=>"NZ", :name=>"New Zealand", :alpha3=>"NZL"},
      {:alpha2=>"NI", :name=>"Nicaragua", :alpha3=>"NIC"},
      {:alpha2=>"NE", :name=>"Niger", :alpha3=>"NER"},
      {:alpha2=>"NG", :name=>"Nigeria", :alpha3=>"NGA"},
      {:alpha2=>"NU", :name=>"Niue", :alpha3=>"NIU"},
      {:alpha2=>"NF", :name=>"Norfolk Island", :alpha3=>"NFK"},
      {:alpha2=>"KP", :name=>"North Korea", :alpha3=>"PRK"},
      {:alpha2=>"MP", :name=>"Northern Mariana Islands", :alpha3=>"MNP"},
      {:alpha2=>"NO", :name=>"Norway", :alpha3=>"NOR"},
      {:alpha2=>"OM", :name=>"Oman", :alpha3=>"OMN"},
      {:alpha2=>"PK", :name=>"Pakistan", :alpha3=>"PAK"},
      {:alpha2=>"PW", :name=>"Palau", :alpha3=>"PLW"},
      {:alpha2=>"PS", :name=>"Palestine", :alpha3=>"PSE"},
      {:alpha2=>"PA", :name=>"Panama", :alpha3=>"PAN"},
      {:alpha2=>"PG", :name=>"Papua New Guinea", :alpha3=>"PNG"},
      {:alpha2=>"PY", :name=>"Paraguay", :alpha3=>"PRY"},
      {:alpha2=>"PE", :name=>"Peru", :alpha3=>"PER"},
      {:alpha2=>"PH", :name=>"Philippines", :alpha3=>"PHL"},
      {:alpha2=>"PN", :name=>"Pitcairn", :alpha3=>"PCN"},
      {:alpha2=>"PL", :name=>"Poland", :alpha3=>"POL"},
      {:alpha2=>"PT", :name=>"Portugal", :alpha3=>"PRT"},
      {:alpha2=>"PR", :name=>"Puerto Rico", :alpha3=>"PRI"},
      {:alpha2=>"QA", :name=>"Qatar", :alpha3=>"QAT"},
      {:alpha2=>"RE", :name=>"Reunion", :alpha3=>"REU"},
      {:alpha2=>"RO", :name=>"Romania", :alpha3=>"ROU"},
      {:alpha2=>"RU", :name=>"Russia", :alpha3=>"RUS"},
      {:alpha2=>"RW", :name=>"Rwanda", :alpha3=>"RWA"},
      {:alpha2=>"SH", :name=>"Saint Helena", :alpha3=>"SHN"},
      {:alpha2=>"KN", :name=>"Saint Kitts And Nevis", :alpha3=>"KNA"},
      {:alpha2=>"LC", :name=>"Saint Lucia", :alpha3=>"LCA"},
      {:alpha2=>"PM", :name=>"Saint Pierre And Miquelon", :alpha3=>"SPM"},
      {:alpha2=>"VC", :name=>"Saint Vincent And The Grenadines", :alpha3=>"VCT"},
      {:alpha2=>"SM", :name=>"San Marino", :alpha3=>"SMR"},
      {:alpha2=>"ST", :name=>"Sao Tome And Principe", :alpha3=>"STP"},
      {:alpha2=>"SA", :name=>"Saudi Arabia", :alpha3=>"SAU"},
      {:alpha2=>"SN", :name=>"Senegal", :alpha3=>"SEN"},
      {:alpha2=>"RS", :name=>"Serbia", :alpha3=>"SRB"},
      {:alpha2=>"SC", :name=>"Seychelles", :alpha3=>"SYC"},
      {:alpha2=>"SL", :name=>"Sierra Leone", :alpha3=>"SLE"},
      {:alpha2=>"SG", :name=>"Singapore", :alpha3=>"SGP"},
      {:alpha2=>"SK", :name=>"Slovak Republic", :alpha3=>"SVK"},
      {:alpha2=>"SI", :name=>"Slovenia", :alpha3=>"SVN"},
      {:alpha2=>"SB", :name=>"Solomon Islands", :alpha3=>"SLB"},
      {:alpha2=>"SO", :name=>"Somalia", :alpha3=>"SOM"},
      {:alpha2=>"ZA", :name=>"South Africa", :alpha3=>"ZAF"},
      {:alpha2=>"GS", :name=>"South Georgia And South Sandwich Islands", :alpha3=>"SGS"},
      {:alpha2=>"KR", :name=>"South Korea", :alpha3=>"KOR"},
      {:alpha2=>"ES", :name=>"Spain", :alpha3=>"ESP"},
      {:alpha2=>"LK", :name=>"Sri Lanka", :alpha3=>"LKA"},
      {:alpha2=>"SD", :name=>"Sudan", :alpha3=>"SDN"},
      {:alpha2=>"SR", :name=>"Suriname", :alpha3=>"SUR"},
      {:alpha2=>"SJ", :name=>"Svalbard And Jan Mayen", :alpha3=>"SJM"},
      {:alpha2=>"SZ", :name=>"Swaziland", :alpha3=>"SWZ"},
      {:alpha2=>"SE", :name=>"Sweden", :alpha3=>"SWE"},
      {:alpha2=>"CH", :name=>"Switzerland", :alpha3=>"CHE"},
      {:alpha2=>"SY", :name=>"Syria", :alpha3=>"SYR"},
      {:alpha2=>"TW", :name=>"Taiwan", :alpha3=>"TWN"},
      {:alpha2=>"TJ", :name=>"Tajikistan", :alpha3=>"TJK"},
      {:alpha2=>"TZ", :name=>"Tanzania", :alpha3=>"TZA"},
      {:alpha2=>"TH", :name=>"Thailand", :alpha3=>"THA"},
      {:alpha2=>"TG", :name=>"Togo", :alpha3=>"TGO"},
      {:alpha2=>"TK", :name=>"Tokelau", :alpha3=>"TKL"},
      {:alpha2=>"TO", :name=>"Tonga", :alpha3=>"TON"},
      {:alpha2=>"TT", :name=>"Trinidad And Tobago", :alpha3=>"TTO"},
      {:alpha2=>"TN", :name=>"Tunisia", :alpha3=>"TUN"},
      {:alpha2=>"TR", :name=>"Turkey", :alpha3=>"TUR"},
      {:alpha2=>"TM", :name=>"Turkmenistan", :alpha3=>"TKM"},
      {:alpha2=>"TC", :name=>"Turks And Caicos Islands", :alpha3=>"TCA"},
      {:alpha2=>"TV", :name=>"Tuvalu", :alpha3=>"TUV"},
      {:alpha2=>"UG", :name=>"Uganda", :alpha3=>"UGA"},
      {:alpha2=>"UA", :name=>"Ukraine", :alpha3=>"UKR"},
      {:alpha2=>"AE", :name=>"United Arab Emirates", :alpha3=>"ARE"},
      {:alpha2=>"GB", :name=>"United Kingdom", :alpha3=>"GBR"},
      {:alpha2=>"US", :name=>"United States", :alpha3=>"USA"},
      {:alpha2=>"UM", :name=>"United States Minor Outlying Islands", :alpha3=>"UMI"},
      {:alpha2=>"UY", :name=>"Uruguay", :alpha3=>"URY"},
      {:alpha2=>"UZ", :name=>"Uzbekistan", :alpha3=>"UZB"},
      {:alpha2=>"VU", :name=>"Vanuatu", :alpha3=>"VUT"},
      {:alpha2=>"VA", :name=>"Vatican City (Holy See)", :alpha3=>"VAT"},
      {:alpha2=>"VE", :name=>"Venezuela", :alpha3=>"VEN"},
      {:alpha2=>"VN", :name=>"Vietnam", :alpha3=>"VNM"},
      {:alpha2=>"VG", :name=>"Virgin Islands (British)", :alpha3=>"VGB"},
      {:alpha2=>"VI", :name=>"Virgin Islands (US)", :alpha3=>"VIR"},
      {:alpha2=>"WF", :name=>"Wallis And Futuna Islands", :alpha3=>"WLF"},
      {:alpha2=>"EH", :name=>"Western Sahara", :alpha3=>"ESH"},
      {:alpha2=>"WS", :name=>"Western Samoa", :alpha3=>"WSM"},
      {:alpha2=>"YE", :name=>"Yemen", :alpha3=>"YEM"},
      {:alpha2=>"YU", :name=>"Yugoslavia", :alpha3=>"YUG"},
      {:alpha2=>"ZM", :name=>"Zambia", :alpha3=>"ZMB"},
      {:alpha2=>"ZW", :name=>"Zimbabwe", :alpha3=>"ZWE"}]

  def get_country_name_from_alpha3(alpha3)
    country_map = t.detect { |f| f[:alpha3] == alpha3}
    if !country_map.nil?
      return country_map[:name]
    else
      return nil
    end
  end

  def get_country_name_from_alpha2(alpha2)
    country_map = t.detect { |f| f[:alpha2] == alpha2}
    if !country_map.nil?
      return country_map[:alpha2]
    else
      return nil
    end
  end

  def get_alpha3_code(name)
    country_map = t.detect { |f| f[:name] == name}
    if !country_map.nil?
      return country_map[:alpha3]
    else
      return nil
    end
  end

  def get_alpha2_code(name)
    country_map = t.detect { |f| f[:name] == name}
    if !country_map.nil?
      return country_map[:alpha3]
    else
      return nil
    end
  end

  def is_country_existed(name)
    country_map = t.detect { |f| f[:name] == name}
    if !country_map.nil?
      return true
    else
      return false
    end
  end

end