User-Agent: Microsoft-MacOutlook/0.0.0.160212
Date: Thu, 31 Mar 2016 10:02:51 -0400
Subject: testSampleMSGFile
From: "Singh, Shilpi (NIH/NCI) [C]" <singhs10@mail.nih.gov>
Message-ID: <5D3EA85B-990D-4C8D-ACA9-EE9867767419@mail.nih.gov>
Thread-Topic: testSampleMSGFile
Mime-version: 1.0
Content-type: multipart/alternative;
	boundary="B_3542263390_338459874"

> This message is in MIME format. Since your mail reader does not understand
this format, some or all of this message may not be legible.

--B_3542263390_338459874
Content-type: text/plain;
	charset="UTF-8"
Content-transfer-encoding: 7bit




Upload document Test sample file

CTRP AUM - Test MSG Document


--B_3542263390_338459874
Content-type: text/html;
	charset="UTF-8"
Content-transfer-encoding: quoted-printable

<html><head></head><body style=3D"word-wrap: break-word; -webkit-nbsp-mode: s=
pace; -webkit-line-break: after-white-space; color: rgb(0, 0, 0); font-size:=
 14px; font-family: Calibri, sans-serif;"><div><div><div><br></div><div><div=
 id=3D"MAC_OUTLOOK_SIGNATURE"><div><br></div><p style=3D"margin: 0px; font-size:=
 12px; line-height: normal; font-family: Helvetica;">Upload document Test sa=
mple file</p>
<p style=3D"margin: 0px; font-size: 12px; line-height: normal; font-family: H=
elvetica;">CTRP AUM - Test Msg Document</p></div></div></div></div></body></=
html>

--B_3542263390_338459874--

