json.extract! @user,
              :username,
              :email,
              :first_name,
              :last_name,
              :middle_name,
              :zipcode,
              :role,
              :organization_id,
              :organization,
              :family_orgs,
              :created_at, :updated_at
