@PA @global
Feature: PA F13 Abstraction Validation

As a CTRP PA Abstractor, I can access the Abstraction Validation to View the Trial History Information Audit Trail

Scenario: #1 Successful Abstraction Validation for a Trial
Given I am logged into the CTRP Protocol Abstraction application
And I have selected a Trial
And I select the Abstraction validation option
When there are no warnings
And there are no errors
Then the 'Abstraction is valid' message displays
And the View Buttons <ViewButtons> type displays
|ViewButtons|
|View XML   |
|View TSR   |


Scenario: #2 Abstraction Validation with warnings or errors
Given I have selected a Trial
And I select the Abstraction validation option
When there are warnings
And there are errors
Then the messages <MessageType> will be displayed in the sequence below

|<MessageType>                                                               |              
|"Abstraction validation failed. Please check Admin Data Menu error(s)."     |
|"Abstraction validation failed. Please check Scientific Data Menu error(s)."|             
|"Abstraction Validation Warning(s)."                                        |             

And the Admin error count will display in the Admin Error display section 
  |"Numbers_items_found" items found, displaying all items.|
And the Scientific error count will display in the Scientific Error display section
   |"Numbers_items_found" items found, displaying all items.|
And the Warning count will display in the warning display section 
    |"Numbers_items_found" items found, displaying all items.|
And the Abstraction Validation warnings and errors triggers will be in the Description field "Description"
And the Abstraction Validation warning and errors AUM related section will be in the comment field in brackets "Comment"
And the AUM Section in the Comment field will be displayed as a link to direct the user to correct the errors and warnings
And the Description and Comment will be grouped by Section


 Scenario: #3 Administration Validation Display for Errors
    Given I have selected a Trial
    And I am on the Abstraction Validation screen
    When the Abstraction Validation button is clicked 
    Then for the Section <Section>, the below Admin Rules <Admin_Error_Rule> will be checked and the screen will display the below description <Description> and comment <Comment> 
   
  |Section                                  |Admin_Error_Rule                                                                                                   |Description                                                                                                                | Comment                                                |                                                                              
  |PAA General Trial Details                | "NCT Number" is more than 30 characters                                                                 	        |NCT Number cannot be more than 30 characters                                                                               |[Select General Trial Details] from Administrative Data menu.	       |
  |PAA General Trial Details                | "CTEP Number" is more than 30 characters	                                                                        |CTEP Number cannot be more than 30 characters                                                                              |[Select General Trial Details] from Administrative Data menu.	       |
  |PAA General Trial Details                | "DCP Number" is more than 30 characters	                                                                        |DCP Number cannot be more than 30 characters                                                                               |[Select General Trial Details] from Administrative Data menu.	       |
  |PAA General Trial Details                | "Lead Organization Trial Identifier" is more than 30 characters                                            	    |Lead Organization Trial Identifier cannot be more than 30 characters	                                                    |[Select General Trial Details] from Administrative Data menu.	|
  |PAA General Trial Details	            |  Lead Organization Trial Identifier is null	                                                                    |Lead Organization is required	                                                                                            |[Select General Trial Details] from Administrative Data menu.	|
  |PAA General Trial Details                |  Keywords is more than 160 characters	                                                                            |Keywords cannot be more than  160 characters	                                                                            |[Select General Trial Details] from Administrative Data menu.	|
  |PAA Regulatory Info – FDAAA	            |  Trial has an associated IND/IDE and Trial Oversight Authority Country is not USA	                                |For IND/IDE protocols, Oversight Authorities must include the Country United States	                                        |	Select [Regulatory Information FDAAA] from Administrative Data menu.  |	
  |PAA Regulatory Info – FDAAA	            |  Trial has an associated IND/IDE and Trial Oversight Authority Organization is not FDA                            |For IND/IDE protocols, Oversight Authorities must include organization: Food and Drug Administration	                    |	Select [Regulatory Information FDAAA] from Administrative Data menu.	|
  |PAA Regulatory Info -Human Subject Safety|  Review Board Approval Status is null	                                                                            |Review Board Approval Status is missing	                                                                            |	Select [Regulatory Information - Human Subject Safety] from Administrative Data menu. |
  |PAA Participating Sites	                |  Duplicate Participating sites	                                                                                |Duplicate Participating Sites are not allowed	                                                                                        |	[Select Participating Sites] from Administrative Data menu.	|
  |PAA Participating Sites	                |  Duplicate Investigators at the same site	                                                                        |Duplicate investigators for same site are not allowed.	                                                                |	[Select Participating Sites] from Administrative Data menu.	|
  |PAA Documents	                        |  ‘Protocol_Document’ Document Type is null for each submission	                                                |Protocol_Document is required	                                                                                        |	[Select Trial Related Documents] from Administrative Data menu.	|
  |PAA Documents	                        |  ‘IRB Approved Document’ Document  Type is null for each submission                                               |IRB Approved document is required	                                                                                    |	[Select Trial Related Documents] from Administrative Data menu.	|
  
    
Scenario Outline: #3a Trial Status Abstraction Validation Errors
    Given I am on the Abstraction Validation Screen
    When Trial Status errors exist
    Then for the <Section>, trial status from <statusFrom>, and  trial status to <statusTo> the below Admin Rules <Description> will be checked and the screen will display the below comment <Comment>
    
|	Section	        |	StatusFrom	                                  |	StatusTo	                                  |	Description	                                                                                                                                                                          |	Comment	|
|	PAA	Trial Status|	In Review	                                  |	In Review	                                  |	ERROR:Duplicate [IN REVIEW] status is not allowed	                                                                                                                                  |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA	Trial Statu |	Approved	                                  |	In Review	                                  |	ERROR: Invalid status transition from [APPROVED] to [IN REVIEW] 	                                                                                                                  |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA	Trial Status|	Approved	                                  |	Approved	                                  |	ERROR:Duplicate [APPROVED] status is not allowed	                                                                                                                                  |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA	Trial Status|	Approved	                                  |	Complete	                                  |	ERROR: Interim status [ACTIVE] is missing\n ERROR: Interim status [CLOSED TO ACCRUAL] is missing\nWarning: Interim status [CLOSED TO ACCRUAL AND INTERVENTION] is missing	          |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status|	Approved	                                  |	Administratively Complete                     |	ERROR: Interim status [ACTIVE] is missing\n ERROR: Interim status [CLOSED TO ACCRUAL] is missing\nWarning: Interim status [CLOSED TO ACCRUAL AND INTERVENTION] is missing	          |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status|	Withdrawn	                                  |	In Review	                                  |	ERROR: Invalid status transition from [WITHDRAWN] to [IN REVIEW] 	                                                                                                                  |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status|	Withdrawn	                                  |	Approved	                                  |	ERROR: Invalid status transition from [WITHDRAWN] to [APPROVED] 	                                                                                                                  |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status|	Withdrawn	                                  |	Withdrawn	                                  |	ERROR: Duplicate [WITHDRAWN] status is not allowed	                                                                                                                                  |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status|	Withdrawn	                                  |	Active	                                      |	ERROR:Invalid status transition from [WITHDRAWN] to [ACTIVE]	                                                                                                                      |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status|	Withdrawn	                                  |	Enrolling By Invitation	                      |	ERROR:Invalid status transition from [WITHDRAWN] to [ENROLLING BY INVITATION]	                                                                                                      |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status| 	Withdrawn	                                  |	Closed to Accrual	                          |	ERROR:Invalid status transition from [WITHDRAWN] to [CLOSED TO ACCRUAL]	                                                                                                              |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status|	Withdrawn	                                  |	Closed to Accrual and Interventions           |	ERROR:Invalid status transition from [WITHDRAWN] to [CLOSED TO ACCRUAL AND INTERVENTIONS]	                                                                                          |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status|	Withdrawn	                                  |	Temporarily Closed to Accrual  	              |	ERROR:Invalid status transition from [WITHDRAWN] to [TEMPORARILY CLOSED TO ACCRUAL]	                                                                                                  |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status|	Withdrawn	                                  |	Temporarily Closed to Accrual and Intervention|	ERROR:Invalid status transition from [WITHDRAWN] to [TEMPORARILY CLOSED TO ACCRUAL AND INTERVENTIONS]	                                                                              |	[Select Trial Status] from Administrative Data menu to view Trial Status. |
|	PAA Trial Status|	Withdrawn	                                  |	Complete	                                  |	ERROR:Invalid status transition from [WITHDRAWN] to [COMPLETE]	                                                                                                                      |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status|	Withdrawn	                                  |	Administratively Complete	                  |	ERROR:Invalid status transition from [WITHDRAWN] to [ADMINISTRATIVELY COMPLETE]	                                                                                                      |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status|	Active	                                      |	In Review	                                  |	ERROR: Invalid status transition from [ACTIVE] to [IN REVIEW]	                                                                                                                      |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status|	Active	                                      |	Approved	                                  |	ERROR: Invalid status transition from [ACTIVE] to [APPROVED]	                                                                                                                      |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status|	Active	                                      |	Active	                                      |	ERROR: Duplicate [ACTIVE] status is not allowed	                                                                                                                                      |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status|	Active	                                      |	Enrolling By Invitation	                      |	ERROR:Invalid status transition from [ACTIVE] to [ENROLLING BY INVITATION]	                                                                                                          |	[Select Trial Status] from Administrative Data menu to view Trial Status.	                     |
|	PAA Trial Status|	Enrolling By Invitation          	          |	In Review	                                  |	ERROR: Invalid status transition from [Enrolling By Invitation] to [IN REVIEW]	                                                                                                      |	[Select Trial Status] from Administrative Data menu to view Trial Status.	                      |
|	PAA Trial Status|	Enrolling By Invitation	                      |	Approved	                                  |	ERROR: Invalid status transition from [Enrolling By Invitation] to [APPROVED]	                                                                                                      |	[Select Trial Status] from Administrative Data menu to view Trial Status.	                      |
|	PAA Trial Status|	Enrolling By Invitation	                      |	Active	                                      |	ERROR: Invalid status transition from [Enrolling by Invitation] to [Active] 	                                                                                                      |	[Select Trial Status] from Administrative Data menu to view Trial Status.	                      |
|	PAA Trial Status|	Enrolling By Invitation	                      |	Enrolling By Invitation                       |	ERROR: Duplicate [Enrolling by Invitation] status is not allowed	                                                                                                                  |	[Select Trial Status] from Administrative Data menu to view Trial Status.	                                  |
|	PAA Trial Status|	Closed to Accrual	                          |	In Review	                                  |	ERROR: Invalid status Transition from [CLOSED TO ACCRUAL] TO [IN REVIEW]	                                                                                                          |	[Select Trial Status] from Administrative Data menu to view Trial Status.	                   |
|	PAA Trial Status|	Closed to Accrual	                          |	Approved	                                  |	ERROR: Invalid status Transition from [CLOSED TO ACCRUAL] TO [APPROVED]	                                                                                                              |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status|	Closed to Accrual	                          |	Withdrawn	                                  |	ERROR: Invalid status Transition from [CLOSED TO ACCRUAL] TO [WITHDRAWN]	                                                                                                          |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status|	Closed to Accrual	                          |	Active	                                      |	ERROR: Invalid status Transition from [CLOSED TO ACCRUAL] TO [ACTIVE]	                                                                                                              |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status|	Closed to Accrual	                          |	Enrolling By Invitation	                      |	ERROR: Invalid status Transition from [CLOSED TO ACCRUAL] TO [ENROLLING BY INVITATION]	                                                                                              |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status|	Closed to Accrual	                          |	Closed to Accrual	                          |	ERROR: Invalid status Transition from [CLOSED TO ACCRUAL] TO [ENROLLING BY INVITATION]	                                                                                              |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status|	Closed to Accrual and Interventions	          |	In Review	                                  |	ERROR: Invalid status Transition from [CLOSED TO ACCRUAL AND INTERVENTIONS] TO [IN REVIEW]	                                                                                          |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status|	Closed to Accrual and Interventions	          |	Approved	                                  |	ERROR: Invalid status Transition from [CLOSED TO ACCRUAL AND INTERVENTIONS] TO [APPROVED]	                                                                                          |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status|	Closed to Accrual and Interventions	          |	Withdrawn	                                  |	ERROR: Invalid status Transition from [CLOSED TO ACCRUAL AND INTERVENTIONS] TO [WITHDRAWN]	                                                                                          |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status|	Closed to Accrual and Interventions           |	Active	                                      |	ERROR: Invalid status Transition from [CLOSED TO ACCRUAL AND INTERVENTIONS] TO [ACTIVE]	                                                                                              |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status|	Closed to Accrual and Interventions	          |	Enrolling By Invitation                       |	ERROR: Invalid status Transition from [CLOSED TO ACCRUAL AND INTERVENTIONS] TO [ENROLLING BY INVITATION]	                                                                          |	[Select Trial Status] from Administrative Data menu to view Trial Status.|
|	PAA Trial Status|	Closed to Accrual and Interventions	          |	Closed to Accrual	                          |	ERROR: Invalid status Transition from [CLOSED TO ACCRUAL AND INTERVENTIONS] TO [CLOSED TO ACCRUAL]	                                                                                  |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status|	Closed to Accrual and Interventions        	  |	Closed to Accrual and Interventions	          |	ERROR: Duplicate [CLOSED TO ACCRUAL AND INTERVENTIONS] status is not allowed	                                                                                                      |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status|	Closed to Accrual and Interventions	          |	Temporarily Closed to Accrual  	              |	ERROR: Invalid status Transition from [CLOSED TO ACCRUAL AND INTERVENTION] TO [TEMPORARILY CLOSED TO ACCRUAL]	                                                                      |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status|	Closed to Accrual and Interventions	          |	Temporarily Closed to Accrual and Intervention|	ERROR: Invalid status Transition from [CLOSED TO ACCRUAL AND INTERVENTIONS] TO [TEMPORARILY CLOSED TO ACCRUAL AND INTERVENTION]                                                       |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status|	Temporarily Closed to Accrual  	              |	In Review	                                  |	ERROR: Invalid status Transition from [TEMPORARILY CLOSED TO ACCRUAL] to [IN REVIEW]	                                                                                              |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status|	Temporarily Closed to Accrual    	          |	Approved	                                  |	ERROR: Invalid status Transition from [TEMPORARILY CLOSED TO ACCRUAL] to [APPROVED]	                                                                                                  |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status|	Temporarily Closed to Accrual  	              |	Withdrawn	                                  |	ERROR: Invalid status Transition from [TEMPORARILY CLOSED TO ACCRUAL] to [WITHDRAWN]	                                                                                              |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status|	Temporarily Closed to Accrual     	          |	Temporarily Closed to Accrual                 |	ERROR: Duplicate [TEMPORARILY CLOSED TO ACCRUAL] status is not allowed	                                                                                                              |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status|	Temporarily Closed to Accrual  	              |	Complete	                                  |	ERROR: Invalid status Transition from [TEMPORARILY CLOSED TO ACCRUAL] to [COMPLETE]	                                                                                                  |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status|	Temporarily Closed to Accrual and Intervention|	In Review	                                  |	ERROR: Invalid status Transition from [TEMPORARILY CLOSED TO ACCRUAL AND INTERVENTION] to [IN REVIEW]	                                                                              |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status|	Temporarily Closed to Accrual and Intervention|	Approved	                                  |	ERROR: Invalid status Transition from [TEMPORARILY CLOSED TO ACCRUAL AND INTERVENTION] to [APPROVED]	                                                                              |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status|	Temporarily Closed to Accrual and Intervention|	Withdrawn	                                  |	ERROR: Invalid status Transition from [TEMPORARILY CLOSED TO ACCRUAL AND INTERVENTION] to [WITHDRAWN]	                                                                              |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status|	Temporarily Closed to Accrual and Intervention|	Temporarily Closed to Accrual  	              |	ERROR: Invalid status transition from [TEMPORARILY CLOSED TO ACCRUAL AND INTERVENTION] to [TEMPORARILY CLOSED TO ACCRUAL]	                                                          |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status|	Temporarily Closed to Accrual and Intervention|	Temporarily Closed to Accrual and Intervention|	ERROR: Duplicate [TEMPORARILY CLOSED TO ACCRUAL AND INTERVENTION] status is not allowed	                                                                                              |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status|	Temporarily Closed to Accrual and Intervention|	Complete	                                  |	ERROR: Invalid status Transition from [TEMPORARILY CLOSED TO ACCRUAL AND INTERVENTION] to [COMPLETE]	                                                                              |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status|	Complete	                                  |	In Review	                                  |	ERROR: Invalid status transition from [COMPLETE] to [IN REVIEW]	                                                                                                                      |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status|	Complete	                                  |	Approved	                                  |	ERROR: Invalid status transition from [COMPLETE] to [APPROVED]	                                                                                                                      |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status|	Complete	                                  |	Withdrawn	                                  |	ERROR: Invalid status transition from [COMPLETE] to [WITHDRAWN]	                                                                                                                      |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status|	Complete	                                  |	Active	                                      |	ERROR: Invalid status transition from [COMPLETE] to [ACTIVE]	                                                                                                                      |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status|	Complete	                                  |	Enrolling By Invitation	                      |	ERROR: Invalid status transition from [COMPLETE] to [ENROLLING BY INVITATION]	                                                                                                      |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status|	Complete	                                  |	Closed to Accrual	                          |	ERROR: Invalid status transition from [COMPLETE] to [CLOSED TO ACCRUAL]	                                                                                                              |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status|	Complete	                                  |	Closed to Accrual and Interventions	          |	ERROR: Invalid status transition from [COMPLETE] to [CLOSED TO ACCRUAL AND INTERVENTIONS]	                                                                                          |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status|	Complete	                                  |	Temporarily Closed to Accrual  	              |	ERROR: Invalid status transition from [COMPLETE] to [TEMPORARILY CLOSED TO ACCRUAL]	                                                                                                  |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status|	Complete	                                  |	Temporarily Closed to Accrual and Intervention|	ERROR: Invalid status transition from [COMPLETE] to [TEMPORARILY CLOSED TO ACCRUAL AND INTERVENTION]	                                                                              |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status|	Complete	                                  |	Complete	                                  |	ERROR: Duplicate [COMPLETE] status is not allowed	                                                                                                                                  |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status|	Complete	                                  |	Administratively Complete	                  |	ERROR: Invalid status transition from [COMPLETE] to [ADMINISTRATIVELY COMPLETE]	                                                                                                      |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status|	Administratively Complete	                  |	In Review	                                  |	ERROR: Invalid status Transition from [ADMINISTRATIVELY COMPLETE] to [IN REVIEW]	                                                                                                  |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status|	Administratively Complete	                  |	Approved	                                  |	ERROR: Invalid status Transition from [ADMINISTRATIVELY COMPLETE] to [APPROVED]                                                                                                       |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status|	Administratively Complete	                  |	Withdrawn	                                  |	ERROR: Invalid status Transition from [ADMINISTRATIVELY COMPLETE] to [WITHDRAWN]	                                                                                                  |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status|	Administratively Complete	                  |	Active	                                      |	ERROR: Invalid status Transition from [ADMINISTRATIVELY COMPLETE] to [ACTIVE]	                                                                                                      |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status|	Administratively Complete	                  |	Enrolling By Invitation	                      |	ERROR: Invalid status Transition from [ADMINISTRATIVELY COMPLETE] to [ENROLLING BY INVITATION]	                                                                                      |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status|	Administratively Complete	                  |	Closed to Accrual	                          |	ERROR: Invalid status Transition from [ADMINISTRATIVELY COMPLETE]  to [CLOSED TO ACCRUAL]	                                                                                          |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status|	Administratively Complete	                  |	Closed to Accrual and Interventions	          |	ERROR: Invalid status Transition from [ADMINISTRATIVELY COMPLETE] to [CLOSED TO ACCRUAL AND INTERVENTIONS]	                                                                          |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status|	Administratively Complete	                  |	Temporarily Closed to Accrual  	              |	ERROR: Invalid status Transition from [ADMINISTRATIVELY COMPLETE] to [TEMPORARILY CLOSED TO ACCRUAL ]	                                                                              |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status|	Administratively Complete	                  |	Temporarily Closed to Accrual and Intervention|	ERROR: Invalid status Transition from [ADMINISTRATIVELY COMPLETE] to [TEMPORARILY  CLOSED TO ACCRUAL AND INTERVENTIONS]	                                                              |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status|	Administratively Complete	                  |	Complete	                                  |	ERROR: Invalid status Transition from [ADMINISTRATIVELY COMPLETE] to [COMPLETE]                                                                                                       |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status|	Administratively Complete	                  |	Administratively Complete	                  |	ERROR: Duplicate [ADMINISTRATIVELY COMPLETE] status is not allowed	                                                                                                                  |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
 

  Scenario:#3b Trial Dates Abstraction Validation Errors
    Given I am on the Abstraction Validation screen
    When Trial Dates Errors exists 
    Then for the Section <Section>, the below Admin Rules <Admin_Error_Rule> will be checked and the screen will display the below description <Description> and comment <Comment> 
   
     |Section         |Admin_Error_Rule                                                                                                         |Description                                                                                                                                       |Comment                                                                      |
     |PAA Trial Status|Trial Status Date is NULL                                                                                                |Each Trial Status must have a Trial Status Date                                                                                                  |[Select Trial Status] from Administrative Data menu to view Trial Status.|                     
     |PAA Trial Status|Trial Status Type is NULL                                                                                                |Trial Status Type must be selected when a Trial Date is entered                                                                                  |[Select Trial Status] from Administrative Data menu to view Trial Status.|
     |PAA Trial Status|Trial Start Date is NULL                                                                                                 |Trial Start Date can not be NULL                                                                                                                |[Select Trial Status] from Administrative Data menu to view Trial Status.|
     |PAA Trial Status|Trial Start Date is the PAST and the Current Trial Status is "IN REVIEW"                                                 |Trial Start Date must be Anticipated when the current Trial Status is "IN REVIEW                                                                 |[Select Trial Status] from Administrative Data menu to view Trial Status.|
     |PAA Trial Status|Trial Start Date is the PAST and the Current Trial Status is "APPROVED"                                                  |Trial Start Date must be Anticipated when the current Trial Status is "APPROVED"                                                                 |[Select Trial Status] from Administrative Data menu to view Trial Status.|
     |PAA Trial Status|Primary Completion Date Tyoe is NULL                                                                                     |Primary Completion Date Type Can not be NULL                                                                                                     |[Select Trial Status] from Administrative Data menu to view Trial Status.|
     |PAA Trial Status|Primary Completion Date Type is "NA" and NCI Division Program Selected is not "DCP"                                      |Primary Completion Date can not be "NA" unless NCI Division Program selected is                                                                  |[Select Trial Status] from Administrative Data menu to view Trial Status.|
     |PAA Trial Status|Trial Dates are in the future and Trial Date Type is Actual                                                              |Future Dates must be Anticipated                                                                                                                 |[Select Trial Status] from Administrative Data menu to view Trial Status.|
    
    Scenario: #4 Scientific Validation Display for Errors
    Given I have selected a Trial
    When the Abstraction Validation button is clicked
    And I am on the Abstraction Validation screen
    Then for the Section <Section>, the below Scientific Rules <Scientific_Error_Rule> will be checked and the screen will display the below description <Description> and comment <Comment> 
    
  |Section               |Scientific_Error_Rule	                                                                                                            |Description                                                                                                                            |Comment                                             |                                                                                                                                                                                                                                                       
  |PAS Trial Design      |Clinical Research Category is 'Interventional' AND Masking is null                                                                |Clinical Research Category is 'Interventional', Masking is required                                                                      |[Select Trial Design] from Scientific Data menu.         |                                                                                                                                                                                                                                                                              
  |PAS Trial Design      |Clinical Research Category is 'Expanded Access' AND Masking is null                                                               |Clinical Research Category is 'Expanded Access', Masking is required                                                                     |[Select Trial Design] from Scientific Data menu.         | 
  |PAS Trial Design      |Clinical Research Category is 'Interventional', Masking is Double blind AND masking roles count is less than two                  |Clinical Research Category is 'Interventional', 'Double blind masking' is selected, at least two masking roles must be specified        |[Select Trial Design] from Scientific Data menu.         | 
  |PAS Trial Design      |Clinical Research Category is 'Expanded Access', Masking is Double blind AND masking roles count is less than two                 |Clinical Research Category is 'Expanded Access', 'Double blind masking' is selected, at least two masking roles must be specified       |[Select Trial Design] from Scientific Data menu.         | 
  |PAS Trial Design	 |Clinical Research Category is‘Interventional’, Masking is ‘single’ AND masking role count not equal to one	                    |Clinical Research Category is ‘Interventional’, 'single blind masking' is selected, there should be only one masking role.	    |	[Select Trial Design] from Scientific Data menu.	     |
  |PAS Trial Design	 |Clinical Research Category is ‘expanded access’, Masking is ‘single’ AND masking role count not equal one                         |Clinical Research Category of‘expanded access’, 'single blind masking' is selected, there should be only one masking role.	    |	[Select Trial Design] from Scientific Data menu.	     |
  |PAS Trial Design	 |Clinical Research Category is ‘Interventional’  AND Intervention Model is null	                                                |Clinical Research Category is 'Interventional' , Intervention Model is required	                                                    |	[Select Trial Design] from Scientific Data menu.	     |
  |PAS Trial Design	 |Clinical Research Category is‘expanded access’ AND Intervention Model is null                           	                        |Clinical Research Category is  'Expanded access', Intervention Model is required	                                                    |	[Select Trial Design] from Scientific Data menu.	     |
  |PAS Trial Design	 |Primary Purpose is null.	                                                                                                        |Primary Purpose is required	                                                                                                        |	[Select Trial Design] from Scientific Data menu.      |
  |PAS Trial Design	 |Primary Purpose is ‘Other’ AND  Primary Purpose Description is null	                                                            |Primary Purpose is ‘Other’, Primary Purpose Description  is required	                                                        |	[Select Trial Design] from Scientific Data menu.	     |
  |PAS Trial Design	 |Trial Phase is null	                                                                                                            |Trial Phase is required	                                                                                                            |	[Select Trial Design] from Scientific Data menu.      |
  |PAS Trial Design	 |Number of Arms / Groups is null	                                                                                                |Number of Arms / Groups is required	                                                                                                |	[Select Trial Design] from Scientific Data menu.      |
  |PAS Trial Design	 |Clinical Research Category is ‘Interventional’ AND Allocations is null	                                                        |Clinical Research Category is 'Interventional' , Allocations is required	                                                            |	[Select Trial Design] from Scientific Data menu.	     |
  |PAS Trial Design	 |Clinical Research Category is ‘expanded access’ AND Allocations is null	                                                        |Clinical Research Category is 'Expanded access', Allocations is required	                                                            |	[Select Trial Design] from Scientific Data menu.	     |
  |PAS Trial Description|Brief Title is null	                                                                                                            |Brief Title is required	                                                                                                            |	[Select Trial Description] from Scientific Data menu. |
  |PAS Trial Description|Brief Title is duplicate 	                                                                                                        |Brief Title must be Unique	                                                                                                        |	[Select Trial Description] from Scientific Data menu. |
  |PAS Trial Description|Brief Summary is null	                                                                                                            |Brief Summary is required	                                                                                                        |	[Select Trial Description] from Scientific Data menu. |
  |PAS Intervention	 |Clinical Research Category is ‘Interventional’, Intervention count is Null 	                                                    |For clinical research Category of ‘Interventional’, at least one Intervention is required        	                                |	[Select Interventions] from Scientific Data menu.	 |
  |PAS Intervention	 |Trial Status is "ACTIVE" AND the status of any "Intervention Name" has an "INACTIVE" status                                       |Intervention term [INTERVENTION NAME] has an "INACTIVE" status.  Another term is required.	                                                    |	[Select Interventions] from Scientific Data menu.	 |
  |PAS arms/groups	     |Arms/Group Type Not Equal to ‘No Intervention’ AND Intervention Assignment for Arm is null 	                                    |Every arm must be assigned one intervention UNLESS ArmS/Group Type is ‘no intervention’ 	                                            |	[Select Arms/ Groups] from Scientific Data menu.	     |
  |PAS arms/groups	     |Arm is null	                                                                                                                    |Arms/Groups are missing 	                                                                                                        |	[Select Arms/Groups] from Scientific Data menu.	|
  |PAS Arms/intervention|Every INTERVENTION NAME not included in any ARM 	                                                                                |Every intervention must be associated with at least one Arm. 	                                                                    |	[Select Arms/ Groups] from Scientific Data menu.	     |
  |PAS Eligibility	     |Eligibility Criteria is null	                                                                                                    |Eligibility Criteria is required	                                                                                                |	[Select Eligibility] from Scientific Data menu.	     |
  |PAS Eligibility 	 |Accepts Healthy Volunteers on Eligibility is null	                                                                                |Accepts Healthy Volunteers is required	                                                                                            |	[Select Eligibility] from Scientific Data menu.	     |
  |PAS Eligibility 	 |Gender is null	                                                                                                                |Gender is required	                                                                                                                |	[Select Eligibility] from Scientific Data menu.	     |
  |PAS Eligibility 	 |Minimum Age and Unit are null	                                                                                                    |Minimum Age and Unit is required	                                                                                                |	[Select Eligibility] from Scientific Data menu.	     |
  |PAS Eligibility 	 |Maximum Age and Unit are null	                                                                                                    |Minimum Age and Unit is required	                                                                                                    |	[Select Eligibility] from Scientific Data menu.	     |
  |PAS Eligibility 	 |Other Criteria is null	                                                                                                        |At least one Other Criteria is required	                                                                                            |	[Select Eligibility] from Scientific Data menu.	     |
  |PAS Eligibility	     |Clinical Research Category is ‘Observational’ AND Sampling Method is null 	                                                    |Clinical Reasearch Category is ‘Observational’, Sampling Method is required	                                                    |	[Select Eligibility] from Scientific Data menu.	     |
  |PAS Eligibility	     |Clinical Research Category is ‘Ancillary Correlative’ AND Sampling Method is null 	                                            |Clinical Reasearch Category is ‘Ancillary Correlative’, Sampling Method is required	                                            |	[Select Eligibility] from Scientific Data menu.	     |
  |PAS Eligibility	     |Clinical Reasearch Category of ‘Observational’  AND  Study Population Description is null	                                        |Clinical Reasearch Category of ‘Observational’ , Study Population Description is required	                                    |	[Select Eligibility] from Scientific Data menu.	     |
  |PAS Eligibility	     |Clinical Reasearch Category of‘Ancillary Correlative’ AND  Study Population Description is null	                                |Clinical Reasearch Category of  ‘Ancillary Correlative’, Study Population Description is required                                |	[Select Eligibility] from Scientific Data menu.	     |
  |PAS Disease	         |Disease/Condition is null	                                                                                                        |At least one Disease/Condition must be entered	                                                                                    |	[Select Diseases/Conditions] from Scientific Data menu.|
  |PAS Disease	         |Trial Status is ACTIVE and any  Disease/Condition status has an "INACTIVE" status	                                                |Disease/Condition [DISEASE NAME] has an "INACTIVE" status . Another term is required.	                                                            |	[Select Diseases/Conditions] from Scientific Data menu.|
  |PAS Outcome	         |Primary Outcome is null	                                                                                                        |At least one primary outcome is required	                                                                                            |	[Select Outcome Measures] from Scientific Data menu.	   |
 
Scenario Outline: #4a Trial Status Abstraction Validation Warnings
    Given I am on the Abstraction Validation Screen
    When Trial Status warnings exist
    Then for the <Section>, trial status from <statusFrom>, and  trial status to <statusTo> the below Admin Rules <Description> will be checked and the screen will display the below comment <Comment>
    
|	Section	            |	StatusFrom	                                    |	StatusTo	                                    |	Description                                                                                                                                      	                                                                                                                                        |	Comment	|
|	PAA Trial Status 	|	STATUSZERO	                                    |	In Review	                                    |	WARNING: Interim status [In Review] is missing	                                                                                                                                                                                                                                            |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status 	|	STATUSZERO	                                    |	Withdrawn	                                    |	WARNING: Interim status [In Review] is missing\nWARNING: Interim status [Approved] is missing	                                                                                                                                                                                            |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status 	|	STATUSZERO	                                    |	Active	                                        |	WARNING: Interim status [In Review] is missing\nWARNING: Interim status [Approved] is missing	                                                                                                                                                                                            |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status 	|	STATUSZERO	                                    |	Enrolling By Invitation            	            |	WARNING: Interim status [In Review] is missing\nWARNING: Interim status [Approved] is missing	                                                                                                                                                                                            |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status 	|	STATUSZERO	                                    |	Closed to Accrual	                            |	WARNING: Interim status [In Review] is missing\nWARNING: Interim status [Approved] is missing\nWARNING: Interim status [Active] is missing	                                                                                                                                                |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status 	|	STATUSZERO	                                    |	Closed to Accrual and Interventions	            |	WARNING: Interim status [In Review] is missing\nWARNING: Interim status [Approved] is missing\nWARNING: Interim status [Active] is missing\nWARNING: Interim status [Closed to Accrual] is missing	                                                                                        |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status 	|	STATUSZERO	                                    |	Temporarily Closed to Accrual     	            |	WARNING: Interim status [In Review] is missing\nWARNING: Interim status [Approved] is missing\nWARNING: Interim status [Active] is missing	                                                                                                                                                |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status 	|	STATUSZERO	                                    |	Temporarily Closed to Accrual and Intervention	|	WARNING: Interim status [In Review] is missing\nWARNING: Interim status [Approved] is missing\nWARNING: Interim status [Active] is missing\nWARNING: Interim status [Temporarily Closed to Accrual]  is missing	                                                                            |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status 	|	STATUSZERO	                                    |	Complete	                                    |	WARNING: Interim status [In Review] is missing\nWARNING: Interim status [Approved] is missing\nWARNING: Interim status [Active] is missing\nWARNING: Interim status [Closed to Accrual] is missing\nWARNING: Interim status [Closed to Accrual and Interventions] is missing	            |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status 	|	STATUSZERO	                                    |	Administratively Complete	                    |	WARNING: Interim status [In Review] is missing\nWARNING: Interim status [Approved] is missing\nWARNING: Interim status [Active] is missing\nWARNING: Interim status [Closed to Accrual] is missing\nWARNING: Interim status [Closed to Accrual and Interventions] is missing                |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status 	|	In Review	                                    |	Active	                                        |	WARNING: Interim status [APPROVED] is missing	                                                                                                                                                                                                                                            |	[Select Trial Status] from Administrative Data menu to view Trial Status.	                          |
|	PAA Trial Status 	|	In Review	                                    |	Enrolling By Invitation                      	|	WARNING: Interim status [APPROVED] is missing	                                                                                                                                                                                                                                            |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status 	|	In Review	                                    |	Closed to Accrual	                            |	WARNING: Interim status [ACTIVE] is missing\nWarning: Interim status [APPROVED] is missing	                                                                                                                                                                                                |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status 	|	In Review	                                    |	Closed to Accrual and Interventions	            |	WARNING: Interim status [ACTIVE] is missing\nWarning: Interim status [CLOSED TO ACCRUAL] is missing\nWarning: Interim status [APPROVED] is missing	                                                                                                                                        |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status 	|	In Review	                                    |	Temporarily Closed to Accrual  	                |	WARNING: Interim status [ACTIVE] is missing\nWarning: Interim status [APPROVED] is missing	                                                                                                                                                                                                |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status 	|	In Review	                                    |	Temporarily Closed to Accrual and Intervention	|	WARNING: Interim status [ACTIVE] is missing\nWarning: Interim status [APPROVED] is missing\nWarning: Interim status [TEMPORARILY CLOSED TO ACCRUAL] is missing	                                                                                                                            |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status 	|	In Review	                                    |	Complete	                                    |	WARNING: Interim status [ACTIVE] is missing\nWarning: Interim status [CLOSED TO ACCRUAL] is missing\nWarning: Interim status [APPROVED] is missing\nWarning: Interim status [CLOSED TO ACCRUAL AND INTERVENTION] is missing                                                                 |	[Select Trial Status] from Administrative Data menu to view Trial Status.|
|	PAA Trial Status 	|	In Review	                                    |	Administratively Complete	                    |	WARNING: Interim status [ACTIVE] is missing\nWarning: Interim status [CLOSED TO ACCRUAL] is missing\nWarning: Interim status [APPROVED] is missing\nWarning: Interim status [CLOSED TO ACCRUAL AND INTERVENTION] is missing	                                                                |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status 	|	Approved	                                    |	Closed to Accrual	                            |	WARNING: Interim status [ACTIVE] is missing	                                                                                                                                                                                                                                                |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status 	|	Approved	                                    |	Closed to Accrual and Interventions           	|	WARNING: Interim status [ACTIVE] is missing\nWarning: Interim status [CLOSED TO ACCRUAL] is missing                                	                                                                                                                                                        |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status 	|	Approved	                                    |	Temporarily Closed to Accrual  	                |	WARNING: Interim status [ACTIVE] is missing	                                                                                                                                                                                                                                                |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status 	|	Approved	                                    |	Temporarily Closed to Accrual and Intervention	|	WARNING: Interim status [ACTIVE] is missing\nWARNING: Interim status [TEMPORARILY CLOSED TO ACCRUAL] is missing	                                                                                                                                                                            |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status 	|	Active	                                        |	Closed to Accrual	                            |	Warning: Invalid Transition from [Active] to [Closed to Accrual] on the same day	                                                                                                                                                                                                        |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status 	|	Active	                                        |	Closed to Accrual and Interventions	            |	WARNING: Interim status [CLOSED TO ACCRUAL] is missing\n Warning: Invalid Transition from [Active] to [Closed to Accrual and Intervention] on the same day	                                                                                                                                |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status 	|	Active	                                        |	Temporarily Closed to Accrual  	                |	Warning: Invalid Transition from [Active] to [Temporarily Closed to Accrual] on the same day	                                                                                                                                                                                            |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status 	|	Active	                                        |	Temporarily Closed to Accrual and Intervention	|	Warning: Invalid Transition from [Active] to [Temporarily Closed to Accrual and Intervention] on the same day	                                                                                                                                                                            |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status 	|	Active	                                        |	Complete	                                    |	WARNING: Interim status [CLOSED TO ACCRUAL] is missing\nWarning: Interim status [CLOSED TO ACCRUAL AND INTERVENTION] is missing	                                                                                                                                                            |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status 	|	Active	                                        |	Administratively Complete	                    |	WARNING: Interim status [CLOSED TO ACCRUAL] is missing\nWarning: Interim status [CLOSED TO ACCRUAL AND INTERVENTION] is missing	                                                                                                                                                            |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status 	|	Enrolling By Invitation	                        |	Closed to Accrual and Interventions	            |	WARNING: Interim status [CLOSED TO ACCRUAL] is missing	                                                                                                                                                                                                                                    |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status 	|	Enrolling By Invitation	                        |	Complete	                                    |	WARNING: Interim status [CLOSED TO ACCRUAL] is missing\nWarning: Interim status [CLOSED TO ACCRUAL AND INTERVENTION] is missing                  	                                                                                                                                        |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status 	|	Enrolling By Invitation	                        |	Administratively Complete	                    |	WARNING: Interim status [CLOSED TO ACCRUAL] is missing\nWarning: Interim status [CLOSED TO ACCRUAL AND INTERVENTION] is missing	                                                                                                                                                            |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status 	|	Closed to Accrual	                            |	Temporarily Closed to Accrual  	                |	WARNING:Invalid Status transition from [CLOSED TO ACCRUAL] to [TEMPORARILY CLOSED TO ACCRUAL]	                                                                                                                                                                                            |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status 	|	Closed to Accrual	                            |	Temporarily Closed to Accrual and Intervention	|	WARNING:Invalid Status transition from [CLOSED TO ACCRUAL] to [TEMPORARILY CLOSED TO ACCRUAL AND INTERVENTION]	                                                                                                                                                                            |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status 	|	Closed to Accrual	                            |	Complete	                                    |	WARNING: Interim status [CLOSED TO ACCRUAL AND INTERVENTION] is missing	                                                                                                                                                                                                                    |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status 	|	Closed to Accrual	                            |	Administratively Complete	                    |	WARNING: Interim status [CLOSED TO ACCRUAL AND INTERVENTION] is missing	                                                                                                                                                                                                                    |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status 	|	Temporarily Closed to Accrual  	                |	Administratively Complete	                    |	WARNING: Interim status [CLOSED TO ACCRUAL] is missing\nWarning: Interim status [CLOSED TO ACCRUAL AND INTERVENTION] is missing	                                                                                                                                                            |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status 	|	Temporarily Closed to Accrual and Intervention	|	Closed to Accrual and Interventions	            |	WARNING: Interim status [CLOSED TO ACCRUAL] is missing	                                                                                                                                                                                                                                    |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|
|	PAA Trial Status 	|	Temporarily Closed to Accrual and Intervention	|	Administratively Complete	                    |	WARNING: Interim status [ CLOSED TO ACCRUAL ] is missing\nWarning: Interim status [CLOSED TO ACCRUAL AND INTERVENTION] is missing	                                                                                                                                                        |	[Select Trial Status] from Administrative Data menu to view Trial Status.	|




 Scenario: #5 Validation Display for Warnings
    Given I have selected a Trial
    And I am on the Abstraction Validation screen
    When the Abstraction Validation button is clicked
    Then for the Section <Section>, the below Warning RUles <Warning_Rule> will be checked and the screen will display the below description <Description> and comment <Comment>
    
|Section                                            |Warning_Rule	                                                                                                                                    |Description                                                                                                                                                    |Comment                                         |                                                                                                                                                                                                                                                         
|PAA General Trial Details                          |Official Title null                                                                                                                                |Official Title is blank                                                                                                                                    |[Select General Trial Details] from Administrative Data menu. |                                                                                                                                                                                                                                                                            
|PAA General Trial Details	                        |Principal Investigator  is null	                                                                                                                |Principal Investigator is blank	                                                                                                                        |	[Select General Trial Details] from Administrative Data menu.	|
|PAA General Trial Details	                        |Sponsor is null	                                                                                                                                |Sponsor is blank	                                                                                                                                        |	[Select General Trial Details] from Administrative Data menu.	|
|PAA General Trial Details	                        |contact is PI or Person or General, email address and phone number is null	                                                                        |Contact Email address and phone number are blank	                                                                                                        |	[Select General Trial Details] from Administrative Data menu.	|
|PAA Collaborators	                                |Duplicate collaborators	                                                                                                                        |Duplicate collaborators are not allowed                                                                                                                  	|	[Select Collaborators] from Administrative Data menu.	|
|PAA On Hold	                                    |Off Hold date is future date	                                                                                                                    |Off Hold Dates must be current or past dates	                                                                                                            |   [Select On-hold Info ] from Trial Overview menu.|
|PAA On Hold	                                    |More than 1 On-hold Date exists without Off-hold Date	                                                                                            |Only one On-hold Date without Off-hold Date is allowed	                                                                                                    |	[Select On-hold Info ] from Trial Overview menu.	                            |
|PAA Regulatory Information Human Subject Safety	|Current Trial Status IN REVIEW and Board Approval Status is not 'Submitted, Pending'	                                                            |Review Board Approval must be  SUBMITTED PENDING if Trial Status is   IN REVIEW 	                                                                        |	[Select Regulatory Information Human Subject Safety] from Administrative Data menu.	|
|PAA Regulatory Information Human Subject Safety	|Current Trial Status ACTIVE, Board Approval Status is 'Submitted, Denied'	                                                                        |Trial Status cannot be  ACTIVE when the  Review Board Approval is ‘Submitted, Denied’	                                                                    |	[Select Regulatory Information Human Subject Safety] from Administrative Data menu.	|
|PAA Regulatory Information Human Subject Safety	|Board Approval Status is 'Submitted, Denied' and Current Trial Status is approved	                                                                |Review Board is ‘Submitted, Denied’, Trial Status cannot be Approved	                                                                                    |	[Select Regulatory Information Human Subject Safety] from Administrative Data menu.	|
|PAA Regulatory Information Human Subject Safety	|Board Approval status 'Submitted, Pending', Current Trial Status is not IN REVIEW	                                                                |Board Approval Status is 'Submitted, Pending', Current Trial Status must be IN REVIEW                                                                   	|	[Select Regulatory Information Human Subject Safety] from Administrative Data menu.	|
|PAA Regulatory Information Human Subject Safety	|Board Approval Status is ‘submitted, Not required’ And the  current trial status  ACTIVE	                                                        |Current trial status cannot be Active when Board Approval Status is 'Submitted, Not Required' 	                                                            |	[Select Regulatory Information Human Subject Safety] from Administrative Data menu. |
|PAA Regulatory Information Human Subject Safety	|Board Approval Status is ‘Submitted, Pending’  And the  current trial status  ACTIVE	                                                            |Current trial status cannot be Active when Board Approval Status is 'Submitted, Pending'	                                                                |	[Select Regulatory Information Human Subject Safety] from Administrative Data menu.	|
|PAA Regulatory Information Human Subject Safety	|Current trial status is WITHDRAWN and Board Approval status is not ‘SUBMITTED, DENIED’	                                                            |Current trial status is Withdrawn, Board Approval status must be ‘Submitted Denied’                                    	                                |	[Select Regulatory Information Human Subject Safety] from Administrative Data menu.	|
|PAA Trial Funding	                                |'Is this trial  funded by a NCI Grant' = Yes and grant is null, must have a NCI grant record entered  	                                            |A grant is required if the trial is funded by NCI 	                                                                                                        |	[Select Trial Funding] from Administrative Data menu.	|
|PAA Trial Funding	                                |Duplicate Grant (Funding Mechanism, Institute Code, Grant Serial Number) 	                                                                        |Duplicate grants are not allowed	                                                                                                                        |	[Select Trial Funding] from Administrative Data menu.	|
|PAA PARTICIPATING SITES	                        |Trial Status is APPROVED and Site Status is ACTIVE 	                                                                                            |Data inconsistency. No site can recruit patients if the overall recruitment status is 'Approved'	                                                        | 	[Select Participating Sites] from Administrative Data menu.	|
|PAA PARTICIPATING SITES	                        |Trial Status is APPROVED and Site Status is ENROLLING BY INVITATION                                                                	            |Data inconsistency. No site can recruit patients if the overall recruitment status is 'Approved'	                                                        |	[Select Participating Sites] from Administrative Data menu.	|
|PAA PARTICIPATING SITES	                        |Trial Status is IN REVIEW and Site Status is ACTIVE 	                                                                                            |Data inconsistency. No site can recruit patients if the overall recruitment status is 'In Review'	                                                        |	[Select Participating Sites] from Administrative Data menu.	|
|PAA PARTICIPATING SITES	                        |Trial Status is IN REVIEW and Site Status is ENROLLING BY INVITATION	                                                                            |Data inconsistency. No site can recruit patients if the overall recruitment status is 'In Review'	                                                        |	[Select Participating Sites] from Administrative Data menu.	|
|PAA PARTICIPATING SITES	                        |Trial Status is WITHDRAWN and Site Status is ACTIVE 	                                                                                            |Data inconsistency. No site can recruit patients if the overall recruitment status is 'Withdrawn'	                                                        |	[Select Participating Sites] from Administrative Data menu.	|
|PAA PARTICIPATING SITES	                        |Trial Status is WITHDRAWN and Site Status is ENROLLING BY INVITATION                                                         	                    |Data inconsistency. No site can recruit patients if the overall recruitment status is 'Withdrawn'	                                                        |	[Select Participating Sites] from Administrative Data menu.	|
|PAA Participating Sites	                        |Participating Site is null	                                                                                                                        |There are no Active Participating Sites exists for the trial.	                                                                                            |	[Select Participating Sites] from Administrative Data menu.	|
|PAA Participating Sites	                        |Primary Investigator has been set to Nullified	                                                                                                    |Primary Investigator has been Nullified. Primary Investigator is required	                                                                                |	[Select Participating Sites] from Administrative Data menu.	|
|PAA Participating Sites	                        |General Contact is null AND NO primary contact (PI, Person) information for each participating site 	                                            |Each participating site playing treating site role must have primary contact (PI, Person) info for not-completed study if General contact is NULL          |	[Select Participating Sites] from Administrative Data menu.	|
|PAA Participating Sites	                        |Target Accrual is null	                                                                                                                            |Target accrual is required	                                                                                                                                |	[Select Participating Sites] from Administrative Data menu. 	|
|PAA NCI Specific Info	                            |Data Table 4 Funding Sponsor status is null	                                                                                                    |Data Table 4 Funding Sponsor status has been nullified.  Data Table 4 Funding Sponsor is required	                                                        |	[Select [NCI Specific Information] from Administrative Data menu.  	|
|PAS Trial Description	                            |Detailed Description is more than 32000 characters	                                                                                                |Detailed Description cannot be more than 32000 characters	                                                                                                |	[Select Trial Description] from Scientific Data menu.	|
|PAS Trial Description	                            |Brief Title is less than 18 characters	                                                                                                            |Brief Title must be more than 18 characters	                                                                                                            |	[Select Trial Description] from Scientific Data menu.	|
|PAS Trial Description	                            |Brief Title is more than 300 characters                                                                                                            |Brief Title must be less than 300 characters                                                                                                               | [Select Trial Description ] from Scientific Data menu. | 
|PAS Trial Design	                                |Clinical Research Category is‘Observational’ AND  Study Model is null	                                                                            |Clinical Research Category is Observational, Study Model is blank	                                                                                        |	[Select Trial Design] from Scientific Data menu.	     |
|PAS Trial Design	                                |Clinical Research Category is ‘Ancillary Correlative’ AND  Study Model is null	                                                                    |Clinical Research Category is  Ancillary Correlative, Study Model is blank	                                                                                |	[Select Trial Design] from Scientific Data menu.	     |
|PAS Trial Design	                                |Clinical Research Category is ‘Observational’, Study Model is ‘Other’ AND Study Model Description is null   	                                    |Clinical Research Category is Observational ,Study Model is‘Other’, AND Description is required	                                                        |	[Select Trial Design] from Scientific Data menu.	     |
|PAS Trial Design	                                |Clinical Research Category is ‘Ancillary Correlative’, Study Model is‘Other’ AND Study Model Description is null	                                |Clinical Research Category is  Ancillary Correlative, Study Model is ‘Other’, ADN Description is required	                                                |	[Select Trial Design] from Scientific Data menu.	     |
|PAS Trial Design	                                |Clinical Research Category is ‘Observational’, Time Perspective is‘Other’ AND Time Perspective  Description is null	                            |Clinical Research Category is Observational ,Time Perspective is‘Other’, AND Description is required	                                                    |	[Select Trial Design] from Scientific Data menu.	     |
|PAS Trial Design	                                |Clinical Research Category is‘Ancillary Correlative’, Time Perspective is‘Other’ AND Time Perspective  Description is null	                        |Clinical Research Category is  Ancillary Correlative,Time Perspective is‘Other’, AND Description is required                                               |	[Select Trial Design] from Scientific Data menu.	     |
|PAS arms/groups	                                |Arm is null	                                                                                                                                    |Arms/Groups are missing 	                                                                                                                                |	[Select Arms/Groups] from Scientific Data menu.	|
|PAS arms/groups	                                |Arm Label is more than 62 characters	                                                                                                            |Arm label cannot be more than 62 characters                                                                                                              	|	[Select Arms/Groups] from Scientific Data menu.	|
|PAS Biomarkers	                                    |The status of any Biomarker is pending	                                                                                                            |At least one pending biomarker exists on the trial.                                                                              	                        |	[Select Biomarkers] from Scientific Data menu.	|

